### ISSUE TITLE
FQN-TO-JAR map is incorrect

### ISSUE THREAD

**Issue by rohan-achar** [Mondego/SourcererJBF#1]
When the jar has relative paths, the relative path links propagate into the fqns. We are losing fqns this way. The proper way to deal with them would be to clean up relative path links first, then extract the fqns.

**Comment by crista** [comment]
Yes, but check first what is it that javac does. If javac can't find these FQNs, neither should we.
This comment is especially relevant for paths that are clearly wrong such as ....../foo

**Comment by rohan-achar** [comment]
Fixed in f683bb0. Have to verify if it is fixed. Will reopen if it isn't.
